version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  my_job:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - print_pipeline_id
  
  failed_cont:   
       
        command: |
            echo "I will exit fail status"
            exit 1
        
        command: |
            echo "I am result of above failed job"
        when: on_fail

workflows:
  pipeline_workflow:
    jobs
      - my_job
      - failed_cont
